CREATE TABLE `relatorio` (
  `ID` varchar(40) NOT NULL,
  `Data` date NOT NULL,
  `Material` varchar(45) NOT NULL,
  `Titulo` varchar(100) NOT NULL,
  `Cliente` varchar(100) NOT NULL,
  `Valor` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
SELECT * FROM `handspike-media`.relatorio;